# Generated by Django 5.2.5 on 2025-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="channels_created",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
