# Generated by Django 5.2.5 on 2025-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="nick",
            field=models.CharField(default="@GawrGura", max_length=10),
            preserve_default=False,
        ),
    ]
