# Generated by Django 5.2.5 on 2025-08-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0002_channel_nick"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="subscribers",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="channel",
            name="nick",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
