# Generated by Django 5.2.5 on 2025-08-29 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0003_channel_subscribers_alter_channel_nick"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
