# Generated by Django 5.2.5 on 2025-08-31 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0004_channel_banner_channel_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="nick",
        ),
        migrations.AddField(
            model_name="channel",
            name="contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="channel",
            name="handle",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="links",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="channel",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
