# Generated by Django 5.2.5 on 2025-09-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0005_remove_channel_nick_channel_contact_channel_handle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
