# Generated by Django 5.2.5 on 2025-09-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0006_alter_channel_icon_alter_channel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
    ]
