# Generated by Django 5.2.5 on 2025-09-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0007_alter_channel_banner_alter_channel_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
